/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cn_core_upgrade_Bspatch */

#ifndef _Included_org_cn_core_upgrade_Bspatch
#define _Included_org_cn_core_upgrade_Bspatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cn_core_upgrade_Bspatch
 * Method:    bspatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_cn_core_upgrade_Bspatch_bspatch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
