/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cn_core_upgrade_Smart */

#ifndef _Included_org_cn_core_upgrade_Smart
#define _Included_org_cn_core_upgrade_Smart
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cn_core_upgrade_Smart
 * Method:    test
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_cn_core_upgrade_Smart_test
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
