/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cn_core_upgrade_Smart */

/*
 * Class:     org_cn_core_upgrade_Smart
 * Method:    test
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_cn_core_upgrade_Smart_test
  (JNIEnv *env, jclass cls, jstring message) {
    return 123;
}

